/*
-- Query: SELECT * FROM thenewsc_core.country
-- Date: 2015-01-25 08:29
*/
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (13,'Afganistán',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (17,'Albania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (23,'Alemania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (26,'Armenia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (27,'Aruba',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (29,'Bosnia-Herzegovina',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (31,'Burkina Fasso',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (37,'Andorra',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (40,'Angola',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (41,'Anguilla',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (43,'Antigua Y Barbuda',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (47,'Antillas Holandesas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (53,'Arabia Saudita',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (59,'Argelia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (63,'Argentina',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (69,'Australia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (72,'Austria',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (74,'Azerbaijan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (77,'Bahamas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (80,'Bahrein',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (81,'Bangladesh',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (83,'Barbados',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (87,'Belgica',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (88,'Belice',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (90,'Bermudas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (91,'Belarus',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (93,'Birmania (Myanmar)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (97,'Bolivia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (101,'Botswana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (105,'Brasil',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (108,'Brunei Darussalam',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (111,'Bulgaria',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (115,'Burundi',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (119,'Butan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (127,'Cabo Verde',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (137,'Caiman, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (141,'Camboya (Kampuchea)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (145,'Camerun, Republica Unida Del',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (149,'Canada',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (159,'Santa Sede',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (165,'Cocos (Keeling), Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (169,'Colombia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (173,'Comoras',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (177,'Congo',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (183,'Cook, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (187,'Corea (Norte), Republica Popular Democratica De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (190,'Corea (Sur), Republica De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (193,'Costa de Marfil',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (196,'Costa Rica',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (198,'Croacia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (199,'Cuba',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (203,'Chad',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (211,'Chile',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (215,'China',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (218,'Taiwan (Formosa)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (221,'Chipre',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (229,'Benin',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (232,'Dinamarca',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (235,'Dominica',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (239,'Ecuador',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (240,'Egipto',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (242,'El Salvador',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (243,'Eritrea',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (244,'Emiratos Arabes Unidos',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (245,'Españaa',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (246,'Eslovaquia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (247,'Eslovenia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (249,'Estados Unidos',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (251,'Estonia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (253,'Etiopia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (259,'Feroe, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (267,'Filipinas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (271,'Finlandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (275,'Francia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (281,'Gabon',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (285,'Gambia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (287,'Georgia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (289,'Ghana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (293,'Gibraltar',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (297,'Granada',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (301,'Grecia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (305,'Groenlandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (309,'Guadalupe',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (313,'Guam',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (317,'Guatemala',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (325,'Guayana Francesa',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (329,'Guinea',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (331,'Guinea Ecuatorial',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (334,'Guinea-Bissau',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (337,'Guyana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (341,'Haití',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (345,'Honduras',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (351,'Hong Kong',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (355,'Hungria',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (361,'India',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (365,'Indonesia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (369,'Irak',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (372,'Iran, Republica Islamica Del',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (375,'Irlanda (Eire)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (379,'Islandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (383,'Israel',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (386,'Italia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (391,'Jamaica',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (399,'Japón',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (403,'Jordania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (406,'Kazajstan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (410,'Kenia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (411,'Kiribati',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (412,'Kirguizistan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (413,'Kuwait',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (420,'Laos, Republica Popular Democratica De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (426,'Lesotho',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (429,'Letonia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (431,'Libano',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (434,'Liberia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (438,'Libia (Incluye Fezzan)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (440,'Liechtenstein',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (443,'Lituania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (445,'Luxemburgo',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (447,'Macao',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (448,'Macedonia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (450,'Madagascar',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (455,'Malaysia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (458,'Malawi',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (461,'Maldivas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (464,'Mali',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (467,'Malta',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (469,'Marianas Del Norte, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (472,'Marshall, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (474,'Marruecos',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (477,'Martinica',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (485,'Mauricio',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (488,'Mauritania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (493,'México',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (494,'Micronesia, Estados Federados De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (496,'Moldavia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (497,'Mongolia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (498,'Monaco',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (501,'Monserrat, Isla',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (505,'Mozambique',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (507,'Namibia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (508,'Nauru',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (511,'Navidad (Christmas), Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (517,'Nepal',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (521,'Nicaragua',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (525,'Niger',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (528,'Nigeria',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (531,'Niue, Isla',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (535,'Norfolk, Isla',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (538,'Noruega',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (542,'Nueva Caledonia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (545,'Papuasia Nueva Guinea',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (548,'Nueva Zelandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (551,'Vanuatu',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (556,'Omán',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (566,'Pacifico, Islas (Usa)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (573,'Paises Bajos (Holanda)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (576,'Pakistan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (578,'Palau, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (580,'Panamá',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (586,'Paraguay',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (589,'Perú',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (593,'Pitcairn, Isla',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (599,'Polinesia Francesa',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (603,'Polonia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (607,'Portugal',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (611,'Puerto Rico',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (618,'Qatar',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (628,'Reino Unido',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (640,'Republica Centroafricana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (644,'Republica Checa',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (647,'Republica Dominicana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (660,'Reunión',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (665,'Zimbabwe',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (670,'Rumania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (675,'Ruanda',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (676,'Rusia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (677,'Salomon, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (685,'Sahara Occidental',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (687,'Samoa',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (690,'Samoa Norteamericana',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (695,'San Cristobal Y Nieves',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (697,'San Marino',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (700,'San Pedro Y Miguelon',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (705,'San Vicente Y Las Granadinas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (710,'Santa Elena',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (715,'Santa Lucia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (720,'Santo Tome Y Principe',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (728,'Senegal',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (731,'Seychelles',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (735,'Sierra Leona',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (741,'Singapur',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (744,'Siria, Republica Arabe De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (748,'Somalia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (750,'Sri Lanka',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (756,'Sudafrica, Republica De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (759,'Sudán',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (764,'Suecia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (767,'Suiza',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (770,'Surinam',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (773,'Swazilandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (774,'Tadjikistan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (776,'Tailandia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (780,'Tanzania, Republica Unida De',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (783,'Djibouti',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (787,'Territorio Britanico Del Oceano Indico',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (788,'Timor Del Este',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (800,'Togo',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (805,'Tokelau',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (810,'Tonga',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (815,'Trinidad Y Tobago',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (820,'Tunicia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (823,'Turcas Y Caicos, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (825,'Turkmenistan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (827,'Turquí­a',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (828,'Tuvalu',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (830,'Ucrania',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (833,'Uganda',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (845,'Uruguay',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (847,'Uzbekistan',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (850,'Venezuela',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (855,'Viet Nam',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (863,'Virgenes, Islas (Britanicas)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (866,'Virgenes, Islas (Norteamericanas)',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (870,'Fiji',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (875,'Wallis Y Fortuna, Islas',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (880,'Yemen',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (885,'Yugoslavia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (888,'Zaire',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (890,'Zambia',NOW(),NOW());
INSERT INTO `countries` (`idcountry`,`name`,`created_at`,`updated_at`) VALUES (897,'Zona Neutral Palestina',NOW(),NOW());
